name: pull-request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm ci

      - name: building
        run: yarn build
        env:
          NEXT_PUBLIC_SEGMENT_KEY: '00000000000000000'